import 'package:json_annotation/json_annotation.dart';

part 'users_container.g.dart'; // This will be generated by the build_runner

@JsonSerializable()
class UsersContainer {
  @JsonKey(name: 'id')
  int id;

  @JsonKey(name: 'username')
  String username;

  @JsonKey(name: 'email')
  String email;

  @JsonKey(name: 'address')
  Address? address;

  @JsonKey(name: 'phone')
  String phone;
  @JsonKey(name: 'website')
  String? website;
  @JsonKey(name: 'company')
  Company? company;

  UsersContainer(this.address, this.id, this.phone, this.username, this.email,
      this.company);

  factory UsersContainer.fromJson(Map<String, dynamic> json) =>
      _$UsersContainerFromJson(json);
  Map<String, dynamic> toJson() => _$UsersContainerToJson(this);
}

@JsonSerializable()
class Address {
  @JsonKey(name: 'street')
  String street;

  @JsonKey(name: 'suite')
  String suite;

  @JsonKey(name: 'city')
  String city;

  @JsonKey(name: 'zipcode')
  String zipcode;
  @JsonKey(name: 'geo')
  Geo? geo;

  Address(
    this.street,
    this.suite,
    this.city,
    this.zipcode,
  );

  factory Address.fromJson(Map<String, dynamic> json) =>
      _$AddressFromJson(json);
  Map<String, dynamic> toJson() => _$AddressToJson(this);
}

@JsonSerializable()
class Geo {
  @JsonKey(name: 'lat')
  String lat;

  @JsonKey(name: 'lng')
  String lng;

  Geo(
    this.lat,
    this.lng,
  );

  factory Geo.fromJson(Map<String, dynamic> json) => _$GeoFromJson(json);
  Map<String, dynamic> toJson() => _$GeoToJson(this);
}

@JsonSerializable()
class Company {
  @JsonKey(name: 'name')
  String name;

  @JsonKey(name: 'catchPhrase')
  String catchPhrase;
  @JsonKey(name: 'bs')
  String bs;

  Company(this.name, this.catchPhrase, this.bs);

  factory Company.fromJson(Map<String, dynamic> json) =>
      _$CompanyFromJson(json);
  Map<String, dynamic> toJson() => _$CompanyToJson(this);
}
